# Generated by Django 3.2.6 on 2021-08-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='modified_at',
            new_name='modified_date',
        ),
    ]
