# Generated by Django 3.2.6 on 2021-08-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_rename_modified_at_advert_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
