# Generated by Django 3.2.6 on 2021-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_alter_advert_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
